### ISSUE TITLE
KB container crashing at startup

### ISSUE THREAD

**Issue by belgio99** [belgio99/smartfactory#17] opened 2024-12-03 11:28 UTC
No logs for you guys unfortunately, but container isn't starting!

Exit code is 0 so I think it's not doing anything and just quitting. Check uvicorn, kb.py and file paths!

**Comment by JacopoRaffi** [comment] 2024-12-05 10:20
The problem is just that in the "main" function we didn't start uvicorn. I don't know if we can close this issue(?)

**Comment by belgio99** [comment] 2024-12-05 17:53
Nope guys, still same thing as before. Crashing with exit code 0

**Closed** 2024-12-05 20:08 UTC
Labels: bug
